import Footer from './Footer'
import Header from './Header'
import Head from 'next/head'
import Link from 'next/link'

const Layout = ({ children, title }) => {
    return (

        <div>
            <Head>
                <title>{title}</title>
                <title>Vishal's project</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossOrigin="anonymous" />
            </Head>
            <Header />
            {children}
            <Footer />
        </div>
    )
}

export default Layout